GET http://localhost:3000/api/vehicles/getAll

###

GET http://localhost:3000/api/vehicles/62d4134fbee4d2f2844864b7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzQ4M2I2NjAxMjM5MmIwNmNkMDQ0YSIsImlhdCI6MTY1NzExNTQyNCwiZXhwIjoxNjU3MTE2NDI0fQ.mKr4PS-rIGu6ivovsN6TBBMIvAFrMfWPgoxEVBuNrVI

###

POST http://localhost:3000/api/vehicles/add
Content-Type: application/json

{
    "make" : "FOOOOOOOOOOOORD",
    "model" : "MODEO",
    "year" : 1995
}

###

DELETE http://localhost:3000/vehicles/62c3253e1cde654185254b10

###

PATCH  http://localhost:3000/vehicles/62c32a205254e471c1dd47a0
Content-Type: application/json

{
    "make" : "Ford",
    "model" : "Modeo"
}

###

GET http://localhost:3000/vehicles/62c31d7a25a6ae14f08c47b1

###